version: "2.2"
services:
  mysqldb:
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - achatdb:/var/lib/mysql

  backend:
    build: ./
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
  frontend:
    image: node:16
    working_dir: /src
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - "../myapp/:/src"

volumes:
  achatdb: